baseURL = '/'
languageCode = 'en-us'
title = "The Engineer's Hagakure"
theme = 'PaperMod'

[params]
  author = "David Bour"
  description = "David Bour's blog"

[params.homeInfoParams]
  title = "Hello 👋! I'm David Bour"
  content = ""
