baseURL = '/'
languageCode = 'en-us'
title = "An Engineer's Hagakure"
theme = 'PaperMod'

[params]
  author = "David Bour"
  description = "David Bour's blog"

[params.homeInfoParams]
  title = "Hello 👋! I'm David Bour"
  content = ""

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/david-bour/"
