baseURL = '/'
languageCode = 'en-us'
title = 'Hello 👋! I'm David Bour'
theme = 'beautifulhugo'

[params]
  subtitle = ""
  logo = ""
  favicon = ""
  [params.author]
    name = "David Bour"
  description = "David Bour"
